name: SHUE DESIGN ASSOCIATES
favicon: null
layout_spectrum: 0.48525
typography_spectrum: 0.89116
title: SHUE DESIGN ASSOCIATES
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.6236809350084513
purpose: []
