name: SHUE DESIGN ASSOCIATES
favicon: null
layout_spectrum: 0.48525
typography_spectrum: 0.92367
title: SHUE DESIGN ASSOCIATES
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfddde'
    - '#000400'
    - '#88abeb'
    - '#3b3e45'
    - '#c64026'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.6236809350084513
purpose: []
